### ISSUE TITLE
SDG-Leiste: SDG 1 isn't clickable 

### ISSUE THREAD

**Issue by jengeb** [okfde/2030watch#3]
First item of sdg-bar isn't clickable. Hover (and the expanding behavior) doesn't work either.

![sdgleiste](https://user-images.githubusercontent.com/3831683/40591269-56b1e1fc-620e-11e8-9b3e-a71fa081f666.png)

* Still an issue even if SDG1 would have content and would be shown.

**Comment by z3to** [comment]
Can‘t reproduce the error. For me, the item is clickable.
Tested in Chrome and Firefox on MacOS.

<img width="625" alt="screenshot 2018-06-19 22 33 55" src="https://user-images.githubusercontent.com/5550700/41622806-4858c3ec-7400-11e8-9956-56bcb1508733.png">

**Comment by jengeb** [comment]
An old version of the website can be found here: https://jengeb.github.io/test2030watch/

The bug is reproducible by doing the following steps:
1. Enter https://jengeb.github.io/test2030watch/.
2. Select any of the SDG links on the key image except SDG 1.
3. You see the SDG view including the colored SDG bar. SDG 1 isn't clickable in this state. (If you reload this page SDG 1 shows its expected behavior.)
